# Generated by Django 5.0.4 on 2024-05-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=600)),
                ('heading1', models.CharField(default='', max_length=99)),
                ('content1', models.CharField(default='', max_length=600)),
                ('heading2', models.CharField(default='', max_length=99)),
                ('content2', models.CharField(default='', max_length=600)),
                ('pub_date', models.DateField()),
                ('thumnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
