# Generated by Django 5.0.4 on 2024-05-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='desc',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
